language: python

python:
    - "3.5"
service:
    - postgresql

before_install:
    - export TEST_DATABASE_URL="postgresql://postgres@localhost/test"

install:
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
    - "pip install coveralls"

before_script:
  - psql -c 'create database test;' -U postgres
  - flask db init

script: "python setup.py test"

after_success: "coveralls"
